# Generated by Django 6.0.2 on 2026-05-17 11:01

import django.db.models.deletion
import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_trip_tanker_tripstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.CharField(default=report.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('vehicle-breakdown', 'vehicle-breakdown')], max_length=255)),
                ('message', models.TextField()),
                ('photo', models.URLField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dispatch.trip')),
            ],
        ),
    ]
