# Generated by Django 6.0.2 on 2026-05-17 03:24

import dispatch.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(default=dispatch.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('sensor_status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], max_length=10)),
                ('trip_id', models.CharField(max_length=15, unique=True)),
                ('product_type', models.CharField(choices=[('PMS', 'PMS')], max_length=5)),
                ('seal_number', models.CharField(max_length=15)),
                ('variance', models.IntegerField(default=0)),
                ('requested_volume', models.IntegerField(default=0)),
                ('loaded_volume', models.IntegerField(default=0)),
                ('volume_match', models.CharField(choices=[('confirmed', 'confirmed'), ('unconfirmed', 'unconfirmed')], default='unconfirmed', max_length=11)),
                ('truck_no', models.CharField(max_length=15)),
                ('distance', models.CharField(max_length=15)),
                ('date_from', models.DateTimeField()),
                ('destination', models.CharField(max_length=255)),
                ('estimated_time_arrival', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector_trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
