# Generated by Django 6.0.2 on 2026-05-17 11:01

import dispatch.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tanker',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.CharField(default=dispatch.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('current_status', models.CharField(choices=[('started', 'started'), ('in-transit', 'in-transit'), ('arrival-pending', 'arrival-pending'), ('completed', 'completed')], max_length=255)),
                ('query_status', models.CharField(blank=True, choices=[('on-route', 'on-route')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dispatch.trip')),
            ],
        ),
    ]
