# Generated by Django 6.0.2 on 2026-06-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_trip_tanker_tripstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at']},
        ),
    ]
