# Generated by Django 6.0.2 on 2026-06-13 04:51

import django.db.models.deletion
import inspection.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_trip_tanker_tripstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.CharField(default=inspection.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('valid_documentation', models.BooleanField(default=False)),
                ('tank_seals_intact', models.BooleanField(default=False)),
                ('safe_operating_condition', models.BooleanField(default=False)),
                ('fire_extinguisher', models.BooleanField(default=False)),
                ('license_verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='dispatch.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.CharField(default=inspection.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=255)),
                ('situation_report', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection', to='inspection.inspection')),
            ],
        ),
    ]
