# Generated by Django 6.0.2 on 2026-06-20 14:28

import django.db.models.deletion
import inspection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_alter_trip_options'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionStatus',
            fields=[
                ('id', models.CharField(default=inspection.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('inspection_status', models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('cleared', 'cleared')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_status', to='dispatch.trip')),
            ],
        ),
    ]
