# Generated by Django 6.0.2 on 2026-06-13 04:52

import django.db.models.deletion
import user_settings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.CharField(default=user_settings.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('use_fingerprint', models.BooleanField(default=False)),
                ('use_face_id', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('trip_notifications', models.BooleanField(default=True)),
                ('sms_messages', models.BooleanField(default=False)),
                ('query_alerts', models.BooleanField(default=True)),
                ('sos_sounds', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('in_app_only', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('english', 'english')], default='english', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=10)),
                ('location_services', models.BooleanField(default=True)),
                ('help_center_theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
