# Generated by Django 6.0.2 on 2026-03-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0002_remove_user_address_default_remove_user_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='drivers_id',
            new_name='driver_id',
        ),
    ]
