# Generated by Django 6.0.2 on 2026-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0003_rename_drivers_id_user_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='driver_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
