# Generated by Django 6.0.2 on 2026-03-08 10:04

import athens.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0004_alter_user_driver_id_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=athens.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('emails', models.EmailField(max_length=254)),
                ('medical_history', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13)),
                ('depot_zone', models.CharField(max_length=255)),
                ('drivers_license', models.CharField(max_length=255)),
                ('license_expiry', models.DateField()),
                ('emergency_contact_phone_no', models.CharField(max_length=13)),
                ('profile_picture', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
