# Generated by Django 6.0.2 on 2026-03-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='drivers_license_doc',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nin_doc',
            field=models.URLField(null=True),
        ),
    ]
