# Generated by Django 6.0.2 on 2026-03-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0006_profile_drivers_license_doc_profile_nin_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='drivers_license_doc',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nin_doc',
        ),
    ]
