# Generated by Django 6.0.2 on 2026-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0008_profile_drivers_license_doc_profile_nin_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('inspector', 'inspector')], default='driver', max_length=10),
        ),
    ]
