# Generated by Django 6.0.2 on 2026-04-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0010_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'driver'), ('inspector', 'inspector')], max_length=10),
        ),
    ]
