# Generated by Django 6.0.2 on 2026-04-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0012_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emails',
            new_name='email',
        ),
    ]
