# Generated by Django 6.0.2 on 2026-06-13 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athens', '0013_rename_emails_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='supervisor_contact',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
