# Generated by Django 6.0.2 on 2026-05-17 11:01

import django.db.models.deletion
import queries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_trip_tanker_tripstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResponse',
            fields=[
                ('id', models.CharField(default=queries.models.generate_id, max_length=255, primary_key=True, serialize=False)),
                ('estimated_time_arrival', models.DateTimeField()),
                ('current_status', models.CharField(choices=[('on_route', 'on_route')], max_length=255)),
                ('additional_notes', models.TextField()),
                ('your_response', models.TextField()),
                ('photo', models.URLField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_responses', to='dispatch.tripstatus')),
            ],
        ),
    ]
